linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - godot
    - gofmt
    - bodyclose
    - exportloopref
    - gosec